baseURL = 'https://blog.wang1zhen.top/'
languageCode = 'en-us'
title = "wang1zhen's Homepage"
theme = 'PaperMod'

[markup.goldmark.renderer]
  unsafe = true

[menu]
 [[menu.main]]
    name = "技术/Tech"
    pageRef = "/tech"
    weight = 1
 [[menu.main]]
    name = "学习/Learn"
    pageRef = "/learn"
    weight = 2
 [[menu.main]]
    name = "关于/About"
    pageRef = "/about"
    weight = 10

[params.homeInfoParams]
Title = "Stay Awhile and Listen.<br>英雄请留步，且听我一言。"
Content = ""

[[params.socialIcons]]
name = "github"
url = "https://github.com/wang1zhen/"

[params]
  ShowReadingTime = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  showtoc = true
  tocopen = true
  mainSections = ["tech", "learn"]
