baseURL = 'https://blog.wang1zhen.top/'
languageCode = 'en-us'
title = "wang1zhen's Homepage"
theme = 'PaperMod'

[markup.goldmark.renderer]
  unsafe = true

[menu]
 [[menu.main]]
    name = "技术"
    pageRef = "/tech"
    weight = 1
 [[menu.main]]
    name = "学习"
    pageRef = "/learn"
    weight = 2
 [[menu.main]]
    name = "关于"
    pageRef = "/about"
    weight = 10

[params.homeInfoParams]
Title = "wang1zhen's Homepage"
Content = "May the force be with you."

[[params.socialIcons]]
name = "github"
url = "https://github.com/wang1zhen/"

[params]
  ShowReadingTime = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  showtoc = true
  tocopen = true
