baseURL = 'https://blog.wang1zhen.top/'
languageCode = 'en-us'
title = "wang1zhen's Blog Site"
theme = 'PaperMod'

[markup]
  defaultMarkdownHandler = 'org'

[menu]
 [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 10
